# Generated by Django 5.2.8 on 2025-12-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_tag_options_alter_task_tags'),
    ]

    operations = [
        migrations.RunSQL(
            # Create the join table if it doesn't exist
            sql="""
                CREATE TABLE IF NOT EXISTS tasks_task_tags (
                    id SERIAL PRIMARY KEY,
                    task_id BIGINT NOT NULL,
                    tag_id BIGINT NOT NULL,
                    FOREIGN KEY (task_id) REFERENCES tasks_task(id) ON DELETE CASCADE,
                    FOREIGN KEY (tag_id) REFERENCES tasks_tag(id) ON DELETE CASCADE,
                    UNIQUE(task_id, tag_id)
                );
                
                CREATE INDEX IF NOT EXISTS tasks_task_tags_task_id_idx ON tasks_task_tags(task_id);
                CREATE INDEX IF NOT EXISTS tasks_task_tags_tag_id_idx ON tasks_task_tags(tag_id);
            """,
            reverse_sql="""
                DROP TABLE IF EXISTS tasks_task_tags;
            """
        ),
    ]
